main_branch_name: main
release_url_template: https://github.com/owner/repository/releases/tag/{{version}}
stale_branch_threshold_days: 1
log_display_count: 15
monorepo:
  enabled: false
  project_dirs: []
issue_handling:
  strategy: branch-name
review:
  enabled: false
  default_reviewers: []
  strategy: github-issue
  workflow: null
  rules: []
  labels:
    pending: review-pending
    concern: review-concern
    accepted: review-accepted
    dismissed: review-dismissed
  concern_blocks_status: false
radar:
  enabled: false
  level: file
  on_sync: true
  on_commit: off
  ignore_patterns:
  - '*.lock'
  - '*-lock.*'
  - CHANGELOG.md
ci_check:
  enabled: false
branch_types:
  docs: docs/
  feature: feature_
  release: release_
  ci: ci/
  feat: feat/
  refactor: refactor/
  chore: chore/
  fix: fix/
automatic_tags:
  release_prefix: v
lint:
  conventional_commit_type:
    enabled: true
    allowed_types:
    - build
    - chore
    - ci
    - docs
    - feat
    - fix
    - perf
    - refactor
    - revert
    - style
    - test
  issue_key_missing:
    enabled: false
    pattern: ^[A-Z]+-\d+$
  scope:
    enabled: true
    enforce_lowercase: true
  subject_line_rules:
    max_length: 72
    enforce_lowercase: true
    no_period: true
  body_line_rules:
    max_line_length: 80
    leading_blank: true
