spring:
  application:
    name: ecommerce-bff
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ecommerce-api # Rewrite part for route
              uri: http://localhost:9090
              predicates:
                - Path=/ecommerce-api/** # call from this part for frontend
              filters:
                - RewritePath=/ecommerce-api/?(?<segment>.*), /$\{segment}
            - id: ecommerce-ui
              uri: http://localhost:3000
              predicates:
                - Path=/**
server:
  port: 9092
